d6 bench

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -181,3 +181,60 @@ jobs:
               body: `MoveGen benchmark results:\n\`\`\`\n${decodedContent}\n\`\`\``
             });
 
+  integration_bench:
+    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release') && !contains(github.event.pull_request.labels.*.name, 'ready') && (contains(github.event.pull_request.labels.*.name, 'draft') || github.event.pull_request.reviewers == '') }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Prepare
+        uses: actions/checkout@v4
+
+      - name: Gather rust nightly
+        uses: dtolnay/rust-toolchain@nightly
+
+      - name: apt install valgrind
+        run: |
+          sudo apt-get -y install valgrind
+
+      - name: Checkout PR's Target Branch
+        run: |
+          git fetch origin ${{ github.base_ref }}
+          git checkout ${{ github.base_ref }}
+
+      - name: Run baseline integration benchmark
+        run: |
+          mkdir -p ./target/tmp
+          echo "d6 on TARGET branch:\n---------------------\n" > ./target/tmp/d6.out
+          cargo test --test d6 -- --nocapture &>> ./target/tmp/d6.out || echo "baseline bench failed, continuing anyway..." 
+
+      - name: Checkout source branch
+        run: |
+          git fetch origin ${{ github.head_ref }} 
+          git checkout ${{ github.head_ref }}   
+
+      - name: Run integration benchmark on new code
+        run: |
+          echo "\n\nd6 on SOURCE branch:\n---------------------\n" >> ./target/tmp/d6.out
+          cargo test --test d6 -- --nocapture &>> ./target/tmp/d6.out
+
+      - name: Read Output File
+        id: read-id-output
+        run: |
+          cat ./target/tmp/d6.out
+          content=$(base64 -w 0 ./target/tmp/id_bench.out) # Single-line base64 output
+          echo "content=$content" >> $GITHUB_ENV
+
+      - name: Post Comment with Benchmark Results
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            const decodedContent = Buffer.from(process.env.content, 'base64').toString('utf-8');
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `d6 benchmark results:\n\`\`\`\n${decodedContent}\n\`\`\``
+            });
+
+
